/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconGrommetIconsActions: typeof import('~icons/grommet-icons/actions.jsx')['default']
  const IconGrommetIconsAdd: typeof import('~icons/grommet-icons/add.jsx')['default']
  const IconGrommetIconsCopy: typeof import('~icons/grommet-icons/copy.jsx')['default']
  const IconGrommetIconsFormNextLink: typeof import('~icons/grommet-icons/form-next-link.jsx')['default']
  const IconGrommetIconsFormPreviousLink: typeof import('~icons/grommet-icons/form-previous-link.jsx')['default']
  const IconGrommetIconsMusic: typeof import('~icons/grommet-icons/music.jsx')['default']
  const IconGrommetIconsPan: typeof import('~icons/grommet-icons/pan.jsx')['default']
  const IconGrommetIconsPause: typeof import('~icons/grommet-icons/pause.jsx')['default']
  const IconGrommetIconsPlay: typeof import('~icons/grommet-icons/play.jsx')['default']
  const IconGrommetIconsSave: typeof import('~icons/grommet-icons/save.jsx')['default']
  const IconGrommetIconsSelect: typeof import('~icons/grommet-icons/select.jsx')['default']
  const IconGrommetIconsShare: typeof import('~icons/grommet-icons/share.jsx')['default']
  const IconGrommetIconsShift: typeof import('~icons/grommet-icons/shift.jsx')['default']
  const IconGrommetIconsStop: typeof import('~icons/grommet-icons/stop.jsx')['default']
  const IconGrommetIconsTrash: typeof import('~icons/grommet-icons/trash.jsx')['default']
}
